export const Types = {
  GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
  SET_IS_LOADING: "SET_IS_LOADING",
  CHANGE_CURRENT_PAGE: "CHANGE_CURRENT_PAGE",
  GET_CATEGORIES_LVL_0: "GET_CATEGORIES_LVL_0",
  CLEAR_FILTER_CATEGORIES_LV0: "CLEAR_FILTER_CATEGORIES_LV0",
  FILTER_BY_TYPE: "FILTER_BY_TYPE",
  FILTER_BY_BRAND: "FILTER_BY_BRAND",
  FILTER_BY_RATING: "FILTER_BY_RATING",
  SEARCH_PRODUCT: "SEARCH_PRODUCT",
  GET_CATEGORIES_LVL_1: "GET_CATEGORIES_LVL_1",
};

export const TypesSuccess = {
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  SET_IS_LOADING_SUCCESS: "SET_IS_LOADING_SUCCESS",
  CHANGE_CURRENT_PAGE_SUCCESS: "CHANGE_CURRENT_PAGE_SUCCESS",
  GET_CATEGORIES_LVL_0_SUCCESS: "GET_CATEGORIES_LVL_0_SUCCESS",
  CLEAR_FILTER_CATEGORIES_LV0_SUCCESS: "CLEAR_FILTER_CATEGORIES_LV0_SUCCESS",
  FILTER_BY_TYPE_SUCCESS: "FILTER_BY_TYPE_SUCCESS",
  FILTER_BY_BRAND_SUCCESS: "FILTER_BY_BRAND_SUCCESS",
  FILTER_BY_RATING_SUCCESS: "FILTER_BY_RATING_SUCCESS",
  SEARCH_PRODUCT_SUCCESS: "SEARCH_PRODUCT_SUCCESS",
  GET_CATEGORIES_LVL_1_SUCCESS: "GET_CATEGORIES_LVL_1_SUCCESS",
};
