export const Types = {
  GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
  SET_IS_LOADING: "SET_IS_LOADING",
  CHANGE_CURRENT_PAGE: "CHANGE_CURRENT_PAGE",
  GET_CATEGORIES_LVL_0: "GET_CATEGORIES_LVL_0",
  CLEAR_FILTER_CATEGORIES_LV0: "CLEAR_FILTER_CATEGORIES_LV0",
  FILTER_BY_TYPE: "FILTER_BY_TYPE",
  FILTER_BY_BRAND: "FILTER_BY_BRAND",
};
